services:
  - type: web
    name: fastapi-duck-backend
    env: python
    region: oregon  # Puedes cambiarlo si prefieres otra región
    plan: free
    branch: main  # Asegúrate de que tu branch se llama 'main'
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11  # Puedes cambiarlo si usas otra versión
